### ISSUE TITLE
Alpine based docker

### ISSUE THREAD

**Issue by rgarrigue** [thelounge/docker-lounge#4]
Hi

Following the new repo for TheLounge docker, I duplicate [this issue](https://github.com/thelounge/lounge/issues/39).

I made an alpine based docker for TheLounge, mainly to save space, the result is 23mb. [Here](https://github.com/rgarrigue/docker-thelounge) are the source, and [here](https://hub.docker.com/r/rgarrigue/thelounge/tags/) is the automated build on docker's hub. Feel free to grab the source for mainstream or ignore it.

**Comment by williamboman** [comment]
I find alpine-based images a nightmare to maintain, luckily lounge doesn't use any native extensions (yet) so that makes things a bit easier. Image layering makes the virtual size not that bad as well (ugh `node_modules`). However, if you feel like it, you could open a PR and we can continue from there.
